Numpy is a mathematical library in python by which we can do matrix multiplication, element wise multiplication, we can use sin, cos and other mathematical operation, so lot of mathematical fuctions are avalable in this library

Firstly, we have to import numpy library and whenever we import any module in python we rename it so that is becomes easy when we use numpy functions

In [1]:
import numpy as np

In [2]:
np.absolute(-1)

1

# Few important function in numpy libary

In [6]:
#creating a numpy array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
#dimension of this array
a.shape

(5,)

In [11]:
#2-D array

b= np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [12]:
b.shape

(2, 5)

In [13]:
#taking transpose of array b
b.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [15]:
#matrix multiplication

c = np.dot(b,b.T)
print(c)

[[55 70]
 [70 90]]


In [16]:
np.dot(b.T,b)

array([[ 5,  8, 11, 14, 17],
       [ 8, 13, 18, 23, 28],
       [11, 18, 25, 32, 39],
       [14, 23, 32, 41, 50],
       [17, 28, 39, 50, 61]])

In [19]:
#random module in numpy-- will assign random value when given low, high and size

d = np.random.randint(60,100,10) #will create an array of random values between 60(inclusive) and 100(exclusive) of size 10
print(d)
print(type(d))

[91 79 64 80 88 82 88 86 82 69]
<class 'numpy.ndarray'>


In [20]:
matrix = np.random.randint(2,8,(2,5))  
print(matrix)

[[7 2 5 6 5]
 [2 5 7 7 6]]


In [21]:
np.max(matrix)

7

In [22]:
np.min(matrix)

2

In [29]:
#argmin returns the index of minimum value 
f = np.array([11,2,3,7,8,90])
np.argmin(f)


1

In [30]:
np.argmax(f)

5

In [32]:
#unique function will return all the unique value of array in sorted format

b= np.array([1,3,-8,76,23,0,12,3,23,1])
print(np.unique(b))

[-8  0  1  3 12 23 76]


In [33]:
#unique value along with its frequency
print(np.unique(b,return_counts = True))

(array([-8,  0,  1,  3, 12, 23, 76]), array([1, 1, 2, 2, 1, 2, 1], dtype=int64))


In [36]:
#program to find the number with maximum frequency

numbers  = np.array([2,4,1,77,2,77,77])
cd = np.unique(numbers,return_counts = True)
print(cd)

(array([ 1,  2,  4, 77]), array([1, 2, 1, 3], dtype=int64))


In [38]:
idx = np.argmax(cd[1])
max_freq_number = cd[0][idx]
print(max_freq_number)

77


In [39]:
#slicing arrays
matrix

array([[7, 2, 5, 6, 5],
       [2, 5, 7, 7, 6]])

In [40]:
matrix[0:2,1:3]

array([[2, 5],
       [5, 7]])